# Label reference for aytordev/overseer
# This file documents the label scheme — it is NOT auto-synced.
# To recreate labels, run the gh commands in the project README or CONTRIBUTING guide.

# --- Type ---
- name: "type:feature"
  color: "5EBFCC"
  description: "New capability or enhancement"

- name: "type:bug"
  color: "D73A4A"
  description: "Unexpected behavior"

- name: "type:task"
  color: "7057FF"
  description: "Technical work (refactor, infra, tech debt)"

- name: "type:docs"
  color: "0075CA"
  description: "Documentation improvement"

# --- Scope (monorepo packages) ---
- name: "scope:domain"
  color: "C2E0C6"
  description: "@overseer/domain"

- name: "scope:shared"
  color: "C2E0C6"
  description: "@overseer/shared"

- name: "scope:server"
  color: "C2E0C6"
  description: "apps/server"

- name: "scope:client"
  color: "C2E0C6"
  description: "apps/client"

# --- Phase ---
- name: "phase:a"
  color: "FEF2C0"
  description: "Phase A (Observer)"

- name: "phase:b"
  color: "FEF2C0"
  description: "Phase B (Controller)"

# --- Status ---
- name: "blocked"
  color: "E4E669"
  description: "Blocked by dependency"

# --- Onboarding ---
- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers"
