name: Bug Report
description: Report unexpected behavior
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear summary of the bug
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happens
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node version, browser, etc.
      placeholder: |
        - OS: macOS 15.x
        - Node: 25.x
        - Browser: Chrome 130

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - low
        - medium
        - high
        - critical

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots / logs
      description: Paste screenshots or relevant log output
